name: test suite
on: [push, pull_request]

env:
  UBUNTU_PACKAGES: libusb-1.0.0 libusb-1.0-0-dev libudev-dev

jobs:
  build-and-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: linuxwacom/libwacom/.github/actions/pkginstall@master
        with:
          apt: $UBUNTU_PACKAGES
      - run: cargo test --all-features

  format:
    name: cargo format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check

  release-build:
     name: cargo build --release
     runs-on: ubuntu-22.04
     needs: [build-and-test]
     steps:
       - uses: actions/checkout@v4
       - uses: dtolnay/rust-toolchain@stable
       - uses: linuxwacom/libwacom/.github/actions/pkginstall@master
         with:
           apt: $UBUNTU_PACKAGES
       - run: cargo build --release
       - run: cp target/release/huion-switcher .
       - uses: actions/upload-artifact@v4
         with:
           name: huion-switcher
           path: |
             huion-switcher
             README.md
             *.rules

  create-release:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    needs: [release-build]
    permissions:
      contents: write
    steps:
      - uses: dawidd6/action-download-artifact@v6
        with:
          name: huion-switcher
          skip_unpack: true
      - uses: softprops/action-gh-release@v2
        with:
          files: huion-switcher.zip
